"""empty message

Revision ID: 58ca8558111c
Revises: 0e68d2ebf064
Create Date: 2024-08-28 12:31:47.409159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ca8558111c'
down_revision = '0e68d2ebf064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
