"""empty message

Revision ID: 79b942d8d9cd
Revises: 
Create Date: 2024-08-08 17:04:49.093390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b942d8d9cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medio_de_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forma_pago', sa.String(length=20), nullable=False),
    sa.Column('financiera', sa.String(length=20), nullable=False),
    sa.Column('cuotas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_pais', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRADOR', 'PACIENTE', 'PROFESIONAL', name='rolenum'), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=15), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_consulta', sa.Integer(), nullable=False),
    sa.Column('motivo_consulta', sa.String(length=50), nullable=False),
    sa.Column('id_tipo_consulta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_consulta'], ['tipo_consulta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historia_clinica', sa.TEXT(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto_perfil', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=12), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=15), nullable=False),
    sa.Column('cjpu', sa.String(length=15), nullable=False),
    sa.Column('titulo_habilitante', sa.String(), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ),
    sa.ForeignKeyConstraint(['id_departamento'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmacion', sa.Integer(), nullable=False),
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_consulta'], ['consulta.id'], ),
    sa.ForeignKeyConstraint(['id_medio_pago'], ['medio_de_pago.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario_paciente_profesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comentario'], ['comentario.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['id_profesional'], ['profesional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especialidad_profesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id'], ),
    sa.ForeignKeyConstraint(['id_profesional'], ['profesional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['descripcion'], ['comentario.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['id_profesional'], ['profesional.id'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['reserva.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_consulta_profesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tipo_consulta', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_profesional'], ['profesional.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_consulta'], ['tipo_consulta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_consulta_profesional')
    op.drop_table('notificacion')
    op.drop_table('especialidad_profesional')
    op.drop_table('comentario_paciente_profesional')
    op.drop_table('reserva')
    op.drop_table('profesional')
    op.drop_table('paciente')
    op.drop_table('consulta')
    op.drop_table('ciudad')
    op.drop_table('usuario')
    op.drop_table('tipo_consulta')
    op.drop_table('pais')
    op.drop_table('medio_de_pago')
    op.drop_table('especialidad')
    op.drop_table('departamento')
    op.drop_table('comentario')
    # ### end Alembic commands ###
