"""empty message

Revision ID: 86772e2b433f
Revises: 959f47529698
Create Date: 2024-08-21 18:27:42.267342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86772e2b433f'
down_revision = '959f47529698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'state', ['state_id'], ['id'])

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint('state_professional_id_fkey', type_='foreignkey')
        batch_op.drop_column('professional_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('state_professional_id_fkey', 'professional', ['professional_id'], ['id'])

    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('state_id')

    # ### end Alembic commands ###
