"""empty message

Revision ID: 94439b28f7c4
Revises: fe87cf2b6850
Create Date: 2024-08-08 02:17:29.318452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94439b28f7c4'
down_revision = 'fe87cf2b6850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child')
    op.drop_table('parent')
    # ### end Alembic commands ###
