"""empty message

Revision ID: 959f47529698
Revises: 67d38b8b8e68
Create Date: 2024-08-21 17:58:46.094125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959f47529698'
down_revision = '67d38b8b8e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint('state_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'state', ['state_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('state_id')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('state_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
