"""empty message

Revision ID: c60b1b7340e0
Revises: 5c1a7431b838
Create Date: 2024-08-23 17:44:46.132857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60b1b7340e0'
down_revision = '5c1a7431b838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.alter_column('weekly',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.alter_column('weekly',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
