"""empty message

Revision ID: f32f13809722
Revises: c416a72cfca8
Create Date: 2024-08-27 15:38:30.048225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32f13809722'
down_revision = 'c416a72cfca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_pay_mp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('authorization_code', sa.Integer(), nullable=False),
    sa.Column('date_approved', sa.DateTime(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('id_payment', sa.Integer(), nullable=False),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('email_client', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_pay_mp', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'data_pay_mp', ['data_pay_mp'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_pay_mp')

    op.drop_table('data_pay_mp')
    # ### end Alembic commands ###
